=== marius-wieschollek/passwords-webextension/src/js/Schema/Theme.schema.json
{
    "$id"                 : "https://git.mdns.eu/nextcloud/passwords-webextension/-/raw/master/src/js/Schema/Theme.schema.json",
    "$schema"             : "https://json-schema.org/draft/2020-12/schema",
    "title"               : "Passwords Webapp Schema",
    "type"                : "object",
    "properties"          : {
        "id"       : {
            "type"   : "string",
            "pattern": "[a-z][a-z-]+"
        },
        "label"    : {
            "type": "string"
        },
        "style"    : {
            "type": "boolean"
        },
        "type"     : {
            "type": "string",
            "enum": [ "server", "custom", "system" ]
        },
        "badge"    : {
            "type"                : "object",
            "properties"          : {
                "color-bg": {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "color-fg": {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "icon"    : {
                    "type": [ "string", "null" ],
                    "enum": [ null, "passwords-new", "passwords-new-dark", "passwords-new-light", "passwords", "passwords-dark", "passwords-light", "passwords-outline-dark", "passwords-outline-light" ]
                }
            },
            "required"            : [
                "color-bg",
                "color-fg"
            ],
            "additionalProperties": false
        },
        "font"     : {
            "type"                : "object",
            "properties"          : {
                "family": {
                    "type": "string",
                    "enum": [ "default", "mono", "sans", "serif", "light", "nextcloud", "dyslexic" ]
                },
                "size"  : {
                    "type": "string",
                    "enum": [ "xs", "s", "d", "m", "l", "xl" ]
                }
            },
            "required"            : [
                "family",
                "size"
            ],
            "additionalProperties": false
        },
        "colors"   : {
            "type"                : "object",
            "properties"          : {
                "element-bg"             : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "element-fg"             : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "element-hover-bg"       : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "element-hover-fg"       : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "element-active-bg"      : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "element-active-fg"      : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "element-active-hover-bg": {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "element-active-hover-fg": {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "button-bg"              : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "button-fg"              : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "button-hover-bg"        : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "button-hover-fg"        : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "slider-bg"              : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "slider-fg"              : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "slider-br"              : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "slider-active-bg"       : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "slider-active-fg"       : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "slider-active-br"       : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "info-bg"                : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "info-fg"                : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "warning-bg"             : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "warning-fg"             : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "error-bg"               : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "error-fg"               : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "success-bg"             : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                },
                "success-fg"             : {
                    "type"   : "string",
                    "pattern": "(#[0-9a-f]{6})|inherit"
                }
            },
            "required"            : [
                "info-fg",
                "success-fg",
                "warning-fg",
                "error-fg"
            ],
            "additionalProperties": false
        },
        "variables": {
            "type"                : "object",
            "patternProperties"   : {
                "[a-z][a-z-]+": {
                    "type": [ "string", "number" ]
                }
            },
            "additionalProperties": false
        }
    },
    "required"            : [
        "id",
        "label",
        "type",
        "badge",
        "font",
        "colors"
    ],
    "additionalProperties": false
}

=== marius-wieschollek/passwords-webextension/src/js/Themes/ArcLight.json
{
    "id": "arc-light",
    "label": "ThemeArcLight",
    "type"  : "system",
    "badge" : {
        "color-bg": "#5294E2",
        "color-fg": "#F5F6F7",
        "icon"    : "passwords-new-dark"
    },
    "font"  : {
        "family": "default",
        "size"  : "d"
    },
    "colors": {
        "element-bg"             : "#F5F6F7",
        "element-fg"             : "#5C616C",
        "element-hover-bg"       : "#E7E8EB",
        "element-hover-fg"       : "#5C616C",
        "element-active-bg"      : "#E7E8EB",
        "element-active-fg"      : "#5294E2",
        "element-active-hover-bg": "#E7E8EB",
        "element-active-hover-fg": "#5294E2",
        "button-bg"              : "inherit",
        "button-fg"              : "inherit",
        "button-hover-bg"        : "#5294E2",
        "button-hover-fg"        : "#F5F6F7",
        "slider-bg"              : "#E7E8EB",
        "slider-fg"              : "#5C616C",
        "slider-br"              : "#5C616C",
        "slider-active-bg"       : "#5294E2",
        "slider-active-fg"       : "#F5F6F7",
        "slider-active-br"       : "#5294E2",
        "info-bg"                : "#0c63db",
        "info-fg"                : "#ffffff",
        "warning-bg"             : "#eca700",
        "warning-fg"             : "#ffffff",
        "error-bg"               : "#e9322d",
        "error-fg"               : "#ffffff",
        "success-bg"             : "#46ba61",
        "success-fg"             : "#ffffff"
    }
}

=== marius-wieschollek/passwords-webextension/src/js/Themes/AdaptaLight.json
{
    "id": "adapta-light",
    "label": "ThemeAdaptaLight",
    "type"  : "system",
    "badge" : {
        "color-bg": "#5294E2",
        "color-fg": "#FFFFFF",
        "icon"    : "passwords-new-dark"
    },
    "font"  : {
        "family": "default",
        "size"  : "d"
    },
    "colors": {
        "element-bg"             : "#F5F6F7",
        "element-fg"             : "#5C616C",
        "element-hover-bg"       : "#FFFFFF",
        "element-hover-fg"       : "#5C616C",
        "element-active-bg"      : "#FFFFFF",
        "element-active-fg"      : "#5294E2",
        "element-active-hover-bg": "#FFFFFF",
        "element-active-hover-fg": "#5294E2",
        "button-bg"              : "inherit",
        "button-fg"              : "inherit",
        "button-hover-bg"        : "#5294E2",
        "button-hover-fg"        : "#FFFFFF",
        "slider-bg"              : "#FFFFFF",
        "slider-fg"              : "#5294E2",
        "slider-br"              : "#5294E2",
        "slider-active-bg"       : "#5294E2",
        "slider-active-fg"       : "#FFFFFF",
        "slider-active-br"       : "#5294E2",
        "info-bg"                : "#0c63db",
        "info-fg"                : "#ffffff",
        "warning-bg"             : "#eca700",
        "warning-fg"             : "#ffffff",
        "error-bg"               : "#e9322d",
        "error-fg"               : "#ffffff",
        "success-bg"             : "#46ba61",
        "success-fg"             : "#ffffff"
    }
}

=== marius-wieschollek/passwords-webextension/src/js/Themes/Light.json
{
    "id"    : "light",
    "label" : "ThemeLight",
    "type"  : "system",
    "badge" : {
        "color-bg": "#0652dd",
        "color-fg": "#ffffff",
        "icon"    : null
    },
    "font"  : {
        "family": "default",
        "size"  : "d"
    },
    "colors": {
        "element-bg"             : "#ffffff",
        "element-fg"             : "#000000",
        "element-hover-bg"       : "#ededed",
        "element-hover-fg"       : "#000000",
        "element-active-bg"      : "#ffffff",
        "element-active-fg"      : "#0996f8",
        "element-active-hover-bg": "#ededed",
        "element-active-hover-fg": "#0670cc",
        "button-bg"              : "inherit",
        "button-fg"              : "inherit",
        "button-hover-bg"        : "#0996f8",
        "button-hover-fg"        : "#ffffff",
        "slider-bg"              : "#eeeeee",
        "slider-fg"              : "#ffffff",
        "slider-br"              : "#dcdddd",
        "slider-active-bg"       : "#0060df",
        "slider-active-fg"       : "#ffffff",
        "slider-active-br"       : "#003eaa",
        "info-bg"                : "#0652dd",
        "info-fg"                : "#ffffff",
        "warning-bg"             : "#ffc312",
        "warning-fg"             : "#ffffff",
        "error-bg"               : "#ff3f34",
        "error-fg"               : "#ffffff",
        "success-bg"             : "#05c46b",
        "success-fg"             : "#ffffff"
    }
}

=== marius-wieschollek/passwords-webextension/src/js/Themes/AdaptaTeal.json
{
    "id": "adapta-teal",
    "label": "ThemeAdaptaTeal",
    "type"  : "system",
    "badge" : {
        "color-bg": "#37EE7C",
        "color-fg": "#F9F9FA",
        "icon"    : "passwords-new-light"
    },
    "font"  : {
        "family": "default",
        "size"  : "d"
    },
    "colors": {
        "element-bg"             : "#202023",
        "element-fg"             : "#858586",
        "element-hover-bg"       : "#263238",
        "element-hover-fg"       : "#F9F9FA",
        "element-active-bg"      : "#263238",
        "element-active-fg"      : "#37EE7C",
        "element-active-hover-bg": "#263238",
        "element-active-hover-fg": "#37EE7C",
        "button-bg"              : "inherit",
        "button-fg"              : "inherit",
        "button-hover-bg"        : "#37EE7C",
        "button-hover-fg"        : "#F9F9FA",
        "slider-bg"              : "#263238",
        "slider-fg"              : "#37EE7C",
        "slider-br"              : "#37EE7C",
        "slider-active-bg"       : "#37EE7C",
        "slider-active-fg"       : "#263238",
        "slider-active-br"       : "#37EE7C",
        "info-bg"                : "#0c63db",
        "info-fg"                : "#ffffff",
        "warning-bg"             : "#eca700",
        "warning-fg"             : "#ffffff",
        "error-bg"               : "#e9322d",
        "error-fg"               : "#ffffff",
        "success-bg"             : "#46ba61",
        "success-fg"             : "#ffffff"
    }
}
